### ISSUE TITLE
In v1.3.0, is Ruby 2 requirement necessary?

### ISSUE THREAD

**Issue by scarver2** [rtomayko/rack-cache#124]
Curious, is there a definitive reason for locking the rack-cache gem to Ruby 2.0 dependency? Looking through the commits I have not seen anything specific.

This change has made managing legacy Rails 3 projects more painful since Rails' gemspec is not locked to version 1.2.

**Comment by tkrajcar** [comment]
+1 The fact that this was introduced in a minor version bump instead of major is really unfortunate. It's currently impossible to do a fresh install of Rails 3 on anything older than Ruby 2.0.0 (including JRuby 1.7) since actionpack depends on rack-cache ~> 1.2, which resolves to 1.3, and thus you get an ugly bundler failure.

I know yanking and republishing is a huge pain, but please, please, consider publishing what was formerly 1.3 as 2.0 instead to resolve this issue.

**Comment by artofhuman** [comment]
If rack-cache now depends from ruby 2.0 release must be a major `2.0.0`. Minor release 1.3.0 broken many projects who still use rails 3.1 or 3.2

**Comment by grosser** [comment]
why would you start a new app with rails 3.2 ?
bundler should not use it if the ruby version does not match -> bundler bug
it is not a feature/behavior change -> not a major release ... 'let us hack around a bundler bug / not updating ruby' ... which I'm not really in favor ...

**Comment by grosser** [comment]
it's not breaking the behavior ... it refuses to install, which is something different ...

**Comment by tkrajcar** [comment]
@grosser The situation is not just 'starting a new app with Rails 3.2', it's 'trying to run bundle with no Gemfile.lock with Rails 3.2 included'. So, for example, I work on a gem that tests against Rails 3.2 -- all our CI now fails on older Rubies than 2.0 and JRuby because of this issue, and I have to add an explicit development dependency on rack-cache 1.2. Not ideal.

Bundler is not smart enough to be able to walk backwards through versions and find a previous gem version that meets the ruby version requirements -- not really a 'bug'.

**Comment by artofhuman** [comment]
We have legacy code on rails 3.1. And we have many private gems which tested by appraisals gem on versions 3.1, 3.2, 4.0 and ruby 1.9.3. Now all builds failed because on CI rails 3.1 and 3.2 depend on rack-cache ~> 1.2

**Comment by artofhuman** [comment]
@grosser ruby 2.0 is a broken capability change, for broken capability we should use major version.

**Comment by grosser** [comment]
released 1.3.1 with 1.9 support ... is that good enough ?

**Comment by artofhuman** [comment]
Yes :)

**Comment by tkrajcar** [comment]
@grosser That's helpful, thanks. In my case I still need to add an explicit dependency for 1.2 because we support ree and 1.8.7... but I know that is unusual, and it is VERY helpful to not have to need it for 1.9.3 and JRuby. Thanks!

**Comment by scarver2** [comment]
:+1: Thanks for the fast response and helping out the community by reducing the limitation to 1.9.

**Comment by grosser** [comment]
opened a bundler issue too: https://github.com/bundler/bundler/issues/4046
